<a href="https://colab.research.google.com/github/Rakshitha-source217/Full-stack-development--python/blob/main/numpy(5/5).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=[7,10,12,20]
type(a)
x=np.array(a)
print(a)
np.max(a)
print(max(a))
np.min(a)
print(min(a))
np.mean(a)
print(np.mean(a))

[7, 10, 12, 20]
20
7
12.25


In [ ]:
import numpy as np
x=np.random.randint(2,10,11)
print(x)



[7 5 6 7 5 2 8 9 6 3 9]


In [ ]:
import numpy as np
a=np.sort(x)
print(a)

[2 3 5 5 6 6 7 7 8 9 9]


In [ ]:
import numpy as np
x=np.arange(1,26).reshape(5,5)
print(x)







[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
import numpy as np
list1 = [10, 20, 30]
list2 = [40, 50, 60]
arr = np.array([list1, list2])
col_sum = np.sum(arr, axis=0)
row_mean = np.mean(arr, axis=1)

print("Column Sums:", col_sum)
print("Row Means:", row_mean)